allowedTopologies:
- matchLabelExpressions:
    - key: failure-domain.beta.kubernetes.io/zone
      values:
        - ap-south-1
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp-ours
parameters:
    fsType: ext4
    type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate